### ISSUE TITLE
different instance['context'] in train and test dataset

### ISSUE THREAD

**Issue by DbrRoxane** [shmsw25/qa-hard-em#11]
Hi,

In the train and dev dataset, each instance has a context entry with the format [[w1, w2, wn], [w1, ..., wn]] with each element being a paragraph and each element of this paragraph a token wi. 
In the eval dataset, context entry contrains [[paragraphe_title, paragpraph_id, [w1, ..., wn]]. 

So during the evaluation of test set, the error in prepro.py occurs line 101. 

```
Traceback (most recent call last):
  File "main.py", line 362, in <module>
    main()
  File "main.py", line 205, in main
    tokenizer=tokenizer)
  File "/media/data/roxane/Desktop/nQAchallenge/narrative-reader/qa-hard-em/prepro.py", line 38, in get_dataloader
    logger=logger, args=args, input_file=input_file, debug=args.debug)
  File "/media/data/roxane/Desktop/nQAchallenge/narrative-reader/qa-hard-em/prepro.py", line 101, in read_squad_examples
    paragraph_text = ' '.join(tokens)
TypeError: sequence item 1: expected str instance, int found
```
 Regards,

**Comment by shmsw25** [comment]
Hi @DbrRoxane, this seems to be because the provided processed data was in a wrong format - I am sorry about that. The updated NQ test data is available [here](https://drive.google.com/file/d/1p9UsXC7MoqlTf4g9zyofPopOTIbSY9u0/view?usp=sharing).

**Comment by DbrRoxane** [comment]
Super, thanks! Can you also update trivia test data? I have the same pb :)

**Comment by shmsw25** [comment]
Sorry for the late reply! But when I checked TriviaQA test data, it seems like it has the correct format. Would you check again and see if it still has the problem?

**Comment by DbrRoxane** [comment]
Yes I redownloaded the preprocessed data from the link you give in the README (https://drive.google.com/file/d/1FqTr6NzZf0CQ3FmA2dxF9R-2X0--CmBf/view) and the difference between trivia-test.json ans the others remains.

**Comment by shmsw25** [comment]
Oh, I realized there was an error that I didn't realize. I fixed the problem and re-uploaded it. Sorry about that!

**Comment by DbrRoxane** [comment]
No problem, so this issue is closed!
