### ISSUE TITLE
Evaluate_qa : Unable to find text: ', the [UNK] arrests [UNK] ,' in ', the CIA arrests Newton ,'

### ISSUE THREAD

**Issue by DbrRoxane** [shmsw25/qa-hard-em#14]
Hi Sewon,

I have trained and evaluated your model on my own data. Things look to work OK (still have to analyze some results) but while I run evaluation, I have this kind of log each time the answer we look for is a named entity (which occurs quite a lot in my dataset ... )
`05/19/2020 09:11:44 - INFO - __main__ - Unable to find text: ', the [UNK] arrests [UNK] ,' in ', the CIA arrests Newton ,' `

I guess this is because of BERT. I guess also it affects my results, do you know how to deal with that? If you have the same with Trivia-QA and/or natural question? 

Regards,

**Comment by shmsw25** [comment]
Hi @DbrRoxane, this seems interesting.. this log is supposed to be printed when the de-tokenization of the span doesn't match with the text before tokenization. Do you have any idea where `[UNK]` comes from here? I think BERT is not supposed to UNK any token as it's based on BPE.

**Comment by DbrRoxane** [comment]
Hi, 

This error occured because my data were not in lower case. Maybe you could precise we have to apply .lower() to our data in [this passage ](https://github.com/shmsw25/qa-hard-em#how-to-use-your-own-preprocessed-data) ? 

Thanks,

**Comment by shmsw25** [comment]
Hi, Great to hear you found the issue. I thought the tokenizer takes `do_lower_case` as input and handles lowercasing [here](https://github.com/shmsw25/qa-hard-em/blob/master/main.py#L189) but will update README to highlight that. Thanks for the suggestion!

**Comment by DbrRoxane** [comment]
Hi,

Oh ok, so if I understand well, in order to use our own data, we have to tokenize the context using the BasicTokenizer and any other ! Am I right? 
This is a detail that now sounds obvious but that I simply did not ... integrate.
