### ISSUE TITLE
Using BERT Large

### ISSUE THREAD

**Issue by DbrRoxane** [shmsw25/qa-hard-em#16]
Hi,

I try to switch to use BERT Large on your models, so I have my config,  vocab and pytorch_model.bin ; I switch for this in my params. But I have an error

`06/19/2020 09:28:27 - INFO - __main__ - Loading from bert-large-uncased/pytorch_model.bin
Traceback (most recent call last):
  File "main.py", line 363, in <module>
    main()
  File "main.py", line 229, in main
    model.bert.load_state_dict(state_dict)
  File "/media/data/roxane/anaconda3/envs/hard-em/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BertModel:
        Missing key(s) in state_dict: "embeddings.word_embeddings.weight", "embeddings.position_embeddings.weight", "embeddings.token_type_emb
eddings.weight", "embeddings.LayerNorm.gamma", "embeddings.LayerNorm.beta", "encoder.layer.0.attention.self.query.weight", "encoder.layer.0.at
tention.self.query.bias", "encoder.layer.0.attention.self.key.weight", "encoder.layer.0.attention.self.key.bias", "encoder.layer.0.attention.s
elf.value.weight", `
... and a lot more, and then some unexpected values
`Unexpected key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", "bert.embeddi
ngs.token_type_embeddings.weight", "bert.embeddings.LayerNorm.gamma", "bert.embeddings.LayerNorm.beta", "bert.encoder.layer.0.attention.self.q
uery.weight", "bert.encoder.layer.0.attention.self.query.bias", "bert.encoder.layer.0.attention.self.key.weight", "bert.encoder.layer.0.attent
ion.self.key.bias", "bert.encoder.layer.0.attention.self.value.weight", `

I tried to switch from `model.bert.load_state_dict(state_dict)` to `model.load_state_dict(state_dict)` but now I have 
`  File "main.py", line 230, in main
    model.load_state_dict(state_dict)#torch.load(args.init_checkpoint))
  File "/media/data/roxane/anaconda3/envs/hard-em/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BertForQuestionAnswering:
        Missing key(s) in state_dict: "qa_outputs.weight", "qa_outputs.bias", "qa_classifier.weight", "qa_classifier.bias". 
        Unexpected key(s) in state_dict: "cls.predictions.bias", "cls.predictions.transform.dense.weight", "cls.predictions.transform.dense.bi
as", "cls.predictions.transform.LayerNorm.gamma", "cls.predictions.transform.LayerNorm.beta", "cls.predictions.decoder.weight", "cls.seq_relat
ionship.weight", "cls.seq_relationship.bias". `

Any ideas?

**Comment by shmsw25** [comment]
Hi @DbrRoxane, sorry about the delayed response. It seems like the model in the codes are implemented as a class that has BERT inside as `self.bert = BERT(...)` and you will have to bring pretrained weights to this bert instead of the whole model itself. For example, instead of doing `model.from_pretrained(path_to_checkpoint)`, please do `model.bert.from_pretrained(path_to_checkpoint)`. Let me know if this doesn't solve the problem.
