### ISSUE TITLE
The set of potential logical forms for WikiSQL

### ISSUE THREAD

**Issue by QHZSS** [shmsw25/qa-hard-em#17]
Hi, could you please tell me how to efficiently generate the full set of potential logical forms for WikiSQL dataset? I've tried in this way: enumerate all the possible combination of agg, sel and conds according to the original natural language questions, and then execute them to see if they could get the right answer, add those sqls with right answer to the potential set, but some questions in the trainset have a huge set of potential logical forms,  and the function engine.execute_query() is quite slow, so I'm wondering how you managed to do this, or , did I misunderstand something? Thanks again.

**Comment by shmsw25** [comment]
Hi @QHZSS, saw you closed the issue so not sure if you still need it or not, but [here](https://drive.google.com/file/d/1AvAtTnbnR9m6bnMFu35pvkIYf8j_-0L8/view?usp=sharing) is a script that generates logical forms from WikiSQL (not a cleaned version, but just for reference). For me, it look less than an hour with a single thread so I think the amount of computation is manageable. In case you prefer, we release [the distant supervision data](https://drive.google.com/file/d/1ZHaBbx3VVsQPZrGlmEoc5w-LJRgcGSo-/view?usp=sharing) we obtained from this script.
