### ISSUE TITLE
Evaluation Script for NarrativeQA

### ISSUE THREAD

**Issue by QHZSS** [shmsw25/qa-hard-em#18]
Hi, thanks for sharing the code! Could you please tell me how you evaluate the result of NarrativeQA ?  Can you share the evaluation code of NarrativeQA result if it is convenient? Thanks! Since I noticed that the score you used to evaluate NarrativeQA is the ROUGE-L score but is is not mentioned in the evaluation script in the repo.

**Comment by shmsw25** [comment]
Hi @QHZSS, right, we used rouge-l for NarrativeQA but it wasn't part of this code as it was mainly for open-domain QA.

I used Python rouge package for the evaluation. I simply computed rouge-l score based on two groundtruths annotated on NarrativeQA as follows.

```python
from rouge import Rouge
rouge = Rouge()
score = max([s["rouge-l"]["f"] for s in rouge.get_scores([pred, pred], gts]) # pred is a prediction string and gts is a list of groundtruth answers (should be two strings on NarrativeQA)
```
