### ISSUE TITLE
Where is the code about WikiSql？

### ISSUE THREAD

**Issue by guotong1988** [shmsw25/qa-hard-em#22]
thank you very much

**Comment by shmsw25** [comment]
Thanks for asking. Unfortunately the training code for WikiSQL is not ready as of now, but the code for running inference based on the available checkpoints can be found in the [wikisql branch](https://github.com/shmsw25/qa-hard-em/tree/wikisql). Please refer to #15 for more details on downloading data & checkpoints, setting up with respect to the [original sqlova codebase](https://github.com/naver/sqlova) and the command lines.
