### ISSUE TITLE
Asking for the code about WikiSQL

### ISSUE THREAD

**Issue by youssefmellah** [shmsw25/qa-hard-em#23]
Thank you for sharing this good work.

Can you please provide the code about WikiSQL (for training and evaluating) ? 

Thanks again.

**Comment by shmsw25** [comment]
Hi @youssefmellah, WikiSQL training+evaluation code is provided in [wikisql branch](https://github.com/shmsw25/qa-hard-em/tree/wikisql).

**Comment by youssefmellah** [comment]
Thank you @shmsw25 for your reply.

But I don't think that this is for Weakly supervised ! because in the wikisql branch I found the code of sqlova which is a supervised approach! 

Can you explain?

**Comment by shmsw25** [comment]
Sorry for the delay in responding. For some reason I just saw it. But responding here in case it still matters.

It does contain weakly-supervised training. You are right that most of the part is taken from sqlova. But you can specify `--loss_type` in order to enable weakly-supervised learning. For example, [this line](https://github.com/shmsw25/qa-hard-em/blob/wikisql/train.py#L342) is for MML, and [this line](https://github.com/shmsw25/qa-hard-em/blob/wikisql/train.py#L344) is for hard EM.

**Comment by SCUTykLin** [comment]
It does not contain weakly-supervised all right. See wikisql_model.py  line 917, you calculate the loss with ground-truth. It's weakly-supervised?

**Comment by shmsw25** [comment]
Hi @GreenArrow2017, we are not using the groundtruth SQL query. We calculate potential SQL queries based on the final answer to the question and calculate the loss with respect to then.

**Comment by SCUTykLin** [comment]
nonono
first，you get the ground_truth
![image](https://user-images.githubusercontent.com/34080744/158412648-819d9723-d7ba-4a38-8cf6-3f0fd09945cb.png)
second, you use them to calculate the loss
![image](https://user-images.githubusercontent.com/34080744/158412834-c281abd4-d51b-406a-8e5c-8f0272d27731.png)

And the dataset what you provided do not contain final answer. The dataset what I saw is in https://github.com/salesforce/WikiSQL.git, just contain question and SQL

**Comment by shmsw25** [comment]
It looks like you have misunderstanding on the pipeline. We have a separate preprocessing that calculates potential SQL queries without using the groundtruth, and use that data to train the model. Please refer to [this issue](https://github.com/shmsw25/qa-hard-em/issues/15) for details in the pipeline as well as preprocessing script/preprocessed data. If you have more questions after carefully reviewing the pipeline, please leave an issue. Thanks.
