### ISSUE TITLE
The wikisql is not weakly-supervised

### ISSUE THREAD

**Issue by SCUTykLin** [shmsw25/qa-hard-em#24]
The wikisql is not weakly-supervised. In wikisql_model.py line 917, you calculate the loss with ground truth sql.

**Comment by shmsw25** [comment]
Hi @GreenArrow2017, we are not using the groundtruth SQL query. We calculate potential SQL queries based on the final answer to the question and calculate the loss with respect to then.

**Comment by SCUTykLin** [comment]
nonono
first，you get the ground_truth
![image](https://user-images.githubusercontent.com/34080744/158412648-819d9723-d7ba-4a38-8cf6-3f0fd09945cb.png)
second, you use them to calculate the loss
![image](https://user-images.githubusercontent.com/34080744/158412834-c281abd4-d51b-406a-8e5c-8f0272d27731.png)

And the dataset what you provided do not contain final answer. The dataset what I saw is in https://github.com/salesforce/WikiSQL.git, just contain question and SQL

**Comment by SCUTykLin** [comment]
And I read the annotated file，There is no final answer.
One of them:
{"table_id":"1-13677808-1","phase":1,"question":"What is the environment rating of the country with an overall average rating of 4.7?","question_tok":["What","is","the","environment","rating","of","the","country","with","an","overall","average","rating","of","4.7","?"],"sql":{"sel":6,"conds":[[9,0,"4.7"]],"agg":0},"query":{"sel":6,"conds":[[9,0,"4.7"]],"agg":0},"wvi_corenlp":[[14,14]]}

**Comment by SCUTykLin** [comment]
You say you omit the ground_truth SQL, where the answer you got? The answer is no provided in dataset what u use

**Comment by shmsw25** [comment]
It looks like you have misunderstanding on the pipeline. We have a separate preprocessing that calculates potential SQL queries without using the groundtruth, and use that data to train the model. Please refer to https://github.com/shmsw25/qa-hard-em/issues/15 for details in the pipeline as well as preprocessing script/preprocessed data. If you have more questions after carefully reviewing the pipeline, please leave an issue. Thanks.

**Comment by SCUTykLin** [comment]
I understand. u first got the pesudo-label(SQL) from answer and question, maybe searching? And use the pesudo-label and question to train model right?

**Comment by shmsw25** [comment]
That is correct.

**Comment by SCUTykLin** [comment]
Sorry for my careless and ignorance.

**Comment by shmsw25** [comment]
No worries. Thanks for the question!
