### ISSUE TITLE
local variable 'rel_features' referenced before assignment

### ISSUE THREAD

**Issue by jhyuklee** [shmsw25/qa-hard-em#3]
Hi, thank you for providing this code!
For training on NQ, I ran run.sh script as follows, and got an error as:
```
$ ./run.sh nq first-only
...
10/30/2019 03:53:10 - INFO - __main__ - Saving features to: /data_nfs/camist002/data/preprocessed-open-domain-qa-data/nq-dev-300-40-20.pkl
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    main()
  File "main.py", line 205, in main
    tokenizer=tokenizer)
  File "/home/jinhyuk/github/qa-hard-em/prepro.py", line 53, in get_dataloader
    save_features = {'features': train_features, 'rel_features': rel_features}
UnboundLocalError: local variable 'rel_features' referenced before assignment
...
```

The error comes from the undefined variable `rel_features`. While there is a code for loading saved feature file (`feature_save_path`), the code for saving the feature file seems not working. What should I pass as `rel_features` given `train_features`?

https://github.com/shmsw25/qa-hard-em/blob/d5dee71238f32c225ec9c7c0bd7fb9fae485e8be/prepro.py#L36-L57

Other than that, one minor suggestion for the code:
- please specify the dependency of `tensorflow` package used in `tokenization.py`. It does not work with `tensorflow 2.0`.

Thanks!

**Comment by jhyuklee** [comment]
I guess just removing the `rel_features` variable seems okay.

**Comment by shmsw25** [comment]
Hi @jhyuklee, thanks for your interest in our work and reporting a bug. It is fixed now so I guess it will run fine now.

Also regarding tensorflow, I added the dependency in README---the code was tested in tensorflow 1.3.0.

**Comment by jhyuklee** [comment]
Thanks @shmsw25! Now it works perfectly. One last thing: in the paper, you mentioned that you used the uncased BERT, but run.sh does not use `--do_lower_case`. Thanks.

**Comment by shmsw25** [comment]
Thanks for pointing this out! But I think it will do lowercase since the default value of `--do_lower_case` is `True`.
