### ISSUE TITLE
n_paragraphs

### ISSUE THREAD

**Issue by chen1234yue** [shmsw25/qa-hard-em#4]
I do not understand the function of  parameter ‘n_paragraphs’。When I try to predict ,if the length of  n_paragraphs is more than one, the program will throw an exception in 
"nbest_json =get_nbest_json([pred for pred in prelim_predictions if all([index<n for index in pred.paragraph_index])])" because pred.paragraph_index is not iterable. Could you please help me?

**Comment by shmsw25** [comment]
Hi @chen1234yue, thanks for your interest in our work. It seems to be due to the bug---I fixed it now, so I believe it should be fine now. The purpose of `n_paragraphs` is to compute the answer depending on "how many paragraphs to read at inference time".

**Comment by chen1234yue** [comment]
Thank you so much!
