### ISSUE TITLE
Any results on WikiTableQuestions?

### ISSUE THREAD

**Issue by zhujiangang** [shmsw25/qa-hard-em#5]

**Comment by shmsw25** [comment]
Hi @zhujiangang thanks for your interest. We don't have result on WikiTableQuestions. In fact, we tried to do it but for WikiTableQuestions, it was hard to generate a set of potential logical forms with reasonable coverage. As mentioned in the paper, whether we can obtain a solution set with reasonable size is a strong contraint of our method and it was not possible for many semantic parsing datasets.
