### ISSUE TITLE
No such file or directory: 'preprocessed-open-domain-qa-data/nq-test.json'

### ISSUE THREAD

**Issue by Yueqing-Sun** [shmsw25/qa-hard-em#6]
Hi, thank you for providing this code!
For training on NQ, I ran run.sh script and got an error as:
```shell
12/02/2019 01:23:41 - INFO - __main__ - Loading preprocessed-open-domain-qa-data/nq-test.json
Output directory () already exists and is not empty.
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    main()
  File "main.py", line 207, in main
    tokenizer=tokenizer)
  File "/users5/yqsun/sss/qa-hard-em/prepro.py", line 38, in get_dataloader
    logger=logger, args=args, input_file=input_file, debug=args.debug)
  File "/users5/yqsun/sss/qa-hard-em/prepro.py", line 82, in read_squad_examples
    with open(_input_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed-open-domain-qa-data/nq-test.json'
```
Where can I find this file？

**Comment by shmsw25** [comment]
Hi @1160300901 , thanks for your interest in our work. Sorry, it looks like we did not include the preprocessed data for the test set by mistake. We have updated the preprocessed data now. If you prefer to only download `nq-test.json`, you can download it [here](https://drive.google.com/file/d/10NmM_9en5C3zg-dP1dS02nqmUFuXUb3T/view?usp=sharing).

**Comment by Yueqing-Sun** [comment]
Thank you so much!
